name: CI (Python)

on:
  pull_request:
  push:
    branches-ignore: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python deps
        run: pip install -r requirements.txt

      # NEW: Install CDK CLI
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk@2 && cdk --version

      - name: Tests + coverage
        run: pytest --maxfail=1 --disable-warnings -q --cov=lambda --cov-report=term-missing

      - name: CDK synth
        run: cdk synth
